chat/urls.py
from django.urls import path

from chat import views

app_name = 'chat'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.create_view, name='create'),
    path('room/', views.RoomView.as_view(), name='room'),
    path('redirect/', views.redirect_view, name='redirect'),
    path('enter/', views.enter_view, name='enter'),
]

lobby/urls.py
from django.urls import path

from lobby import views

app_name = 'lobby'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

vrml/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tips/', include('lobby.urls')),
    path('', include('chat.urls')),
]

chat/models.py
from django.db import models

# Create your models here.

lobby/models.py
from django.db import models

# Create your models here.

chat/views.py
from auroravr import gamelift
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.views import generic


class IndexView(generic.TemplateView):
    template_name = 'chat/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['game_sessions'] = gamelift.search(alias_id='alias-784566b2-47e5-43e6-b19a-3271e09efd1f')
        return context


def create_view(request):
    gamelift.create(alias_id='alias-784566b2-47e5-43e6-b19a-3271e09efd1f',
                html=request.build_absolute_uri(reverse('chat:room')), max_player=4)
    return redirect(request.build_absolute_uri(reverse('chat:index')))


def redirect_view(request):
    return redirect(request.build_absolute_uri(reverse('chat:room')))


class RoomView(generic.TemplateView):
    template_name = 'chat/room.html'


def enter_view(request):
    return JsonResponse(gamelift.enter(room_id=request.GET.get('room_arn'), player_id='new'))

lobby/views.py
import os

from django.views import generic

from lobby.aws import gamelift


class IndexView(generic.TemplateView):
    template_name = 'lobby/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['game_sessions'] = gamelift.search()
        return context

chat/templates/chat/index.html
<html>
<body>
<div x="-200" y="-300" l="600" w="{% widthratio game_sessions|length|add:'1' 1 1000 %}" h="400" floor="10">
</div>
{% for session in game_sessions reversed %}
    <div x="400" y="{% widthratio forloop.counter 1 600 %}" l="600" w="500" h="400" floor="10">
        <div x="100" y="0" l="500" w="500" h="380" wall="10"></div>
        <box x="0" y="0" z="0" material="wood"/>
        <box x="0" y="100" z="0" material="wood"/>
        <box x="0" y="300" z="0" material="wood"/>
        <box x="0" y="400" z="0" material="wood"/>
        <box x="0" y="0" z="100" material="wood"/>
        <box x="0" y="100" z="100" material="wood"/>
        <box x="0" y="300" z="100" material="wood"/>
        <box x="0" y="400" z="100" material="wood"/>
        <box x="0" y="0" z="200" material="wood"/>
        <box x="0" y="100" z="200" material="wood"/>
        <box x="0" y="200" z="200" material="wood"/>
        <box x="0" y="300" z="200" material="wood"/>
        <box x="0" y="400" z="200" material="wood"/>
        <text x="-1" y="100" z="230" size="60">{{ session.GameProperties.0.Value }}</text>
        <text x="-1" y="200" z="200" size="30">{{ session.CurrentPlayerSessionCount }} / {{ session.MaximumPlayerSessionCount }}</text>
        <portal x="0" y="200" z="0" href="{{ request.get_host }}{% url 'chat:enter' %}?room_arn={{ session.GameSessionId }}"/>
    </div>
{% endfor %}
    <portal x="-200" y="200" z="0" href="{{ request.get_host }}{% url 'chat:create' %}"/>
</body>
</html>

chat/templates/chat/room.html
<html>
<body>
<div x="-500" y="-500" l="1000" w="1000" h="400" floor="10"></div>
</body>
</html>

lobby/templates/lobby/index.html
<html>
<body>
<div x="-500" y="-500" l="1000" w="{% widthratio game_sessions|length|add:'1' 1 1000 %}" h="400" floor="10" wall="10"
     ceiling="10">
    <box x="0" y="0" z="0" l="1000" w="{% widthratio game_sessions|length|add:'1' 1 1000 %}" h="1" material="marble"/>
    <sphere x="500" y="1600" z="0" w="200" l="200" h="200" material="pine"/>
    <sphere x="600" y="1900" z="0" w="300" l="300" h="300" material="walnut"/>
    <sphere x="600" y="1100" z="0" w="300" l="300" h="300" material="walnut"/>
    <sphere x="500" y="900" z="0" w="200" l="200" h="200" material="pine"/>
</div>

{% for session in game_sessions reversed %}
    <div x="400" y="{% widthratio forloop.counter0 1 600 %}" l="600" w="500" h="400" floor="10">
        <div x="100" y="0" l="500" w="500" h="400" wall="10"></div>
        <box x="0" y="0" z="0" material="brick"/>
        <box x="0" y="100" z="0" material="brick"/>
        <box x="0" y="300" z="0" material="brick"/>
        <box x="0" y="400" z="0" material="brick"/>
        <box x="0" y="0" z="100" material="brick"/>
        <box x="0" y="100" z="100" material="brick"/>
        <box x="0" y="300" z="100" material="brick"/>
        <box x="0" y="400" z="100" material="brick"/>
        <box x="0" y="0" z="200" material="brick"/>
        <box x="0" y="100" z="200" material="brick"/>
        <box x="0" y="200" z="200" material="brick"/>
        <box x="0" y="300" z="200" material="brick"/>
        <box x="0" y="400" z="200" material="brick"/>
        <box x="0" y="0" z="300" material="brick"/>
        <box x="0" y="100" z="300" material="brick"/>
        <box x="0" y="200" z="300" material="brick"/>
        <box x="0" y="300" z="300" material="brick"/>
        <box x="0" y="400" z="300" material="brick"/>
        <img x="-1" y="200" z="280" src="https://s3.ap-northeast-2.amazonaws.com/auroravr-worlds/image/VRML.png"/>
        <text x="-1" y="100" z="200" size="60">{{ session.GameProperties.0.Value }}</text>
        <text x="-1" y="100" z="170" size="30">{{ session.CurrentPlayerSessionCount }} / {{ session.MaximumPlayerSessionCount }}</text>
        <portal x="0" y="200" z="-90" href="{{ session.GameSessionId }}"/>
        <light x="50" y="250" z="190"/>
    </div>
    <div x="-400" y="{% widthratio forloop.counter0 1 600 %}" l="100" w="100" h="400">
        <light x="410" y="250" z="300"/>
        <light x="110" y="250" z="320"/>
        <box x="0" y="200" z="0" material="pine"/>
        <box x="0" y="200" z="100" material="pine"/>
        <box x="0" y="200" z="200" material="pine"/>
        <box x="0" y="200" z="300" material="pine"/>
    </div>
{% endfor %}
</body>
</html>